version: "2"

services:
  front:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    links:
      - mysql:mysql
      - phpmyadmin:phpmyadmin
      - memcached:memcached
      - redis:redis
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
    volumes:
      - ../:/var/www/html
      - ../logs:/var/log/supervisor

  mysql:
  # MySQL 5.8 has issues
    image: mariadb
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456aB
    volumes:
  # Init MySQL
      - ./sql/:/docker-entrypoint-initdb.d/
  # Export error logs    
      - ../logs/mysql:/var/log/mysql
  # Uncomment the following to persist MySQL data.
  #    - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
  ## No need to expose anything, accessed internally through Apache proxy
    links:
      - mysql:db
    environment:
      PMA_USER: root
      PMA_PASSWORD: 123456aB
  # Play nice behind a proxy    
      PMA_ABSOLUTE_URI: http://localhost/phpmyadmin/

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  redis:
    image: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  mysql-data: